# Window settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "My First Game"

# Player settings
PLAYER_SPEED = 200
PLAYER_HEALTH = 100
PLAYER_DAMAGE = 20

# Enemy settings
ENEMY_SPEED = 50
ENEMY_HEALTH = 30
STARTING_ENEMY_COUNT = 5

# Bullet settings
BULLET_SPEED = 500
BULLET_SCALE = 0.2
BULLET_DAMAGE = 10

# Shooting settings
SHOOT_COOLDOWN = 0.25

# Damage settings
INVINCIBILITY_TIME = 1.0

# Score settings
ENEMY_SCORE = 10

# Particle settings
PARTICLE_MIN_SPEED = -100
PARTICLE_MAX_SPEED = 100
PARTICLE_LIFETIME = 0.4
PARTICLE_SHRINK_SPEED = 10
PARTICLE_COUNT = 10