# Window settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "My First Game"

# Player settings
PLAYER_SPEED = 200
PLAYER_HEALTH = 100


# Enemy settings
ENEMY_SPEED = 50
ENEMY_HEALTH = 30
ENEMY_SCORE = 10
ENEMY_DAMAGE = 10
ENEMY_MIN_SPAWN_DISTANCE = 150
STARTING_ENEMY_COUNT = 5

ENEMY_AVOID_SPEED = 50

FAST_ENEMY_SPEED = 100
FAST_ENEMY_HEALTH = 20
FAST_ENEMY_SCORE = 20
FAST_ENEMY_DAMAGE = 15
FAST_ENEMY_ZIGZAG_SPEED = 50
FAST_ENEMY_ZIGZAG_INTERVAL = 0.4

TANK_ENEMY_SPEED = 30
TANK_ENEMY_HEALTH = 50
TANK_ENEMY_SCORE = 30
TANK_ENEMY_DAMAGE = 25
TANK_ENEMY_KNOCKBACK = 150

# Bullet settings
BULLET_SPEED = 500
BULLET_SCALE = 0.2
BULLET_DAMAGE = 10

# Shooting settings
SHOOT_COOLDOWN = 0.25

# Damage settings
INVINCIBILITY_TIME = 1.0

# Particle settings
PARTICLE_MIN_SPEED = -100
PARTICLE_MAX_SPEED = 100
PARTICLE_LIFETIME = 0.4
PARTICLE_SHRINK_SPEED = 10
PARTICLE_COUNT = 10
