# Window settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "My First Game"

# Player settings
PLAYER_SPEED = 200
PLAYER_HEALTH = 100


# Enemy settings
ENEMY_HEALTH_BAR_WIDTH = 40
ENEMY_HEALTH_BAR_HEIGHT = 5

ENEMY_SCALE = 0.2
ENEMY_SPEED = 50
ENEMY_HEALTH = 30
ENEMY_SCORE = 10
ENEMY_DAMAGE = 10

ENEMY_MIN_SPAWN_DISTANCE = 150
ENEMY_SPAWN_MAX_ATTEMPTS = 100

ENEMY_AVOID_SPEED = 50

NORMAL_ENEMY_BASE_CHANCE = 70
FAST_ENEMY_BASE_CHANCE = 15

FAST_ENEMY_SCALE = 0.1
FAST_ENEMY_SPEED = 100
FAST_ENEMY_HEALTH = 20
FAST_ENEMY_SCORE = 20
FAST_ENEMY_DAMAGE = 15
FAST_ENEMY_ZIGZAG_SPEED = 50
FAST_ENEMY_ZIGZAG_INTERVAL = 0.4

TANK_ENEMY_SCALE = 0.5
TANK_ENEMY_SPEED = 30
TANK_ENEMY_HEALTH = 50
TANK_ENEMY_SCORE = 30
TANK_ENEMY_DAMAGE = 25
TANK_ENEMY_KNOCKBACK = 150

# Wave settings
STARTING_ENEMY_COUNT = 5
ENEMIES_ADDED_PER_WAVE = 2
WAVE_DELAY = 2.0

# Bullet settings
BULLET_SPEED = 500
BULLET_SCALE = 0.2
BULLET_DAMAGE = 10

# Shooting settings
SHOOT_COOLDOWN = 0.25

# Power-up settings
POWER_UP_DROP_CHANCE = 0.2
POWER_UP_SPEED=80
POWER_UP_SCALE = 0.02
SHIELD_DURATION = 5.0
RAPID_FIRE_DURATION = 5.0
HEALTH_POWERUP_AMOUNT = 25

# Damage settings
INVINCIBILITY_TIME = 1.0

# Damage number settings
DAMAGE_NUMBER_LIFETIME = 0.5
DAMAGE_NUMBER_SPEED = 30

# Particle settings
PARTICLE_MIN_SPEED = -100
PARTICLE_MAX_SPEED = 100
PARTICLE_LIFETIME = 0.4
PARTICLE_SHRINK_SPEED = 10
PARTICLE_COUNT = 10
